# ============================================================================
# Bookstore API URL Patterns — Complete App
# ============================================================================
# URL patterns for the REST API, generated by DRF router.
# ============================================================================

from rest_framework.routers import DefaultRouter

from .views_api import AuthorViewSet, BookViewSet

router = DefaultRouter()
router.register("books", BookViewSet)
router.register("authors", AuthorViewSet)

urlpatterns = router.urls
