"""Tests for Module 05 / Project 05 — Async Web Server.

Tests the FastAPI async server endpoints using TestClient. Covers the
root endpoint, slow endpoint, aggregate endpoint, background jobs,
streaming response, and health check.

WHY can TestClient test async endpoints?
- FastAPI's TestClient (built on httpx) handles async endpoints transparently.
- It runs the ASGI app synchronously, so you don't need pytest-asyncio here.
- Background tasks run inline during tests (not in a separate thread).
"""

import sys
import os
from unittest.mock import patch

import pytest
from fastapi.testclient import TestClient

sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))

import app as app_module
from app import app

client = TestClient(app)


@pytest.fixture(autouse=True)
def reset_task_log():
    """Clear the task log before each test to avoid cross-test pollution."""
    app_module.task_log.clear()
    yield
    app_module.task_log.clear()


# ---------------------------------------------------------------------------
# Tests for GET /
# ---------------------------------------------------------------------------

def test_root_returns_message():
    """The root endpoint should return a greeting message and a timestamp."""
    response = client.get("/")

    assert response.status_code == 200
    data = response.json()
    assert "message" in data
    assert "Hello" in data["message"]
    assert "time" in data


# ---------------------------------------------------------------------------
# Tests for GET /slow
# ---------------------------------------------------------------------------

def test_slow_endpoint_returns_response():
    """GET /slow should return a response (we mock asyncio.sleep for speed).

    In the real app, this endpoint waits 3 seconds. In tests, we mock
    the sleep to make it instant.
    """
    with patch("app.asyncio.sleep", return_value=None):
        response = client.get("/slow")

    assert response.status_code == 200
    data = response.json()
    assert "message" in data


# ---------------------------------------------------------------------------
# Tests for GET /aggregate
# ---------------------------------------------------------------------------

def test_aggregate_returns_results():
    """GET /aggregate should return results from all three simulated services.

    The endpoint fires three concurrent "API calls" and combines results.
    """
    with patch("app.asyncio.sleep", return_value=None):
        response = client.get("/aggregate")

    assert response.status_code == 200
    data = response.json()
    assert "results" in data
    assert len(data["results"]) == 3
    assert "total_time" in data


def test_aggregate_result_structure():
    """Each result in /aggregate should have source, data, and took fields."""
    with patch("app.asyncio.sleep", return_value=None):
        response = client.get("/aggregate")

    results = response.json()["results"]
    for result in results:
        assert "source" in result
        assert "data" in result
        assert "took" in result


# ---------------------------------------------------------------------------
# Tests for POST /background-job
# ---------------------------------------------------------------------------

def test_background_job_returns_immediately():
    """POST /background-job should return a response immediately.

    The actual work happens in the background after the response is sent.
    """
    response = client.post("/background-job?task_name=test-task")

    assert response.status_code == 200
    data = response.json()
    assert "test-task" in data["message"]


# ---------------------------------------------------------------------------
# Tests for GET /task-log
# ---------------------------------------------------------------------------

def test_task_log_initially_empty():
    """GET /task-log should return an empty list when no jobs have completed."""
    response = client.get("/task-log")

    assert response.status_code == 200
    data = response.json()
    assert data["total"] == 0
    assert data["completed_tasks"] == []


# ---------------------------------------------------------------------------
# Tests for GET /stream
# ---------------------------------------------------------------------------

def test_stream_returns_text():
    """GET /stream should return a streaming text/plain response.

    The response contains numbered lines generated by an async generator.
    """
    with patch("app.asyncio.sleep", return_value=None):
        response = client.get("/stream")

    assert response.status_code == 200
    # The streaming response should contain the generated numbers.
    text = response.text
    assert "Number 1" in text
    assert "Number 10" in text


# ---------------------------------------------------------------------------
# Tests for GET /health
# ---------------------------------------------------------------------------

def test_health_check():
    """GET /health should return a healthy status."""
    response = client.get("/health")

    assert response.status_code == 200
    data = response.json()
    assert data["status"] == "healthy"
