# ============================================================================
# Top-Level URL Configuration — REST Framework Project
# ============================================================================
# This project uses DRF routers to generate API URLs automatically.
# ============================================================================

from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),

    # Include the bookstore API URLs (generated by DRF router).
    path("api/", include("bookstore.urls")),
]
